name: Compile LaTeX

on:
  push:
    branches:
      - main
    paths: ["src/**", .github/workflows/**, compile.sh]

jobs:
  compile:
    name: Compile notes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout current pdfs branch
        uses: actions/checkout@v3
        with:
          ref: pdfs
          path: .currpdfs


      - name: Install LaTeX
        run: |
            sudo apt update
            sudo apt install -y latexmk texlive texlive-science texlive-latex-extra texlive-bibtex-extra biber
        

      - name: Prepare output directory
        run: |
          mkdir .compiled
          cp README.md .compiled
          cp LICENSE .compiled

      - name: Compile
        run: |
          bash ./compile.sh .compiled .currpdfs


      - name: Move to pdfs branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pdfs
          FOLDER: .compiled
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: "github-actions[bot]"
          COMMIT_EMAIL: "github-actions[bot]@users.noreply.github.com"
          MESSAGE: "🤖 Hello human, doing my things ({sha})"