name: Setup web viewer

on:
  push:
    branches:
      - main
    paths: [
      "src/**", 
      .github/prepare_web_viewer.py, 
      .github/workflows/web.yml, 
    ]

jobs:
  compile:
    name: Format web pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Generate web viewer content
        run: |
          python3 ${GITHUB_WORKSPACE}/.github/prepare_web_viewer.py \
            --src-path=${GITHUB_WORKSPACE}/src \
            --out-path=/tmp/webviewer \
            --template-path=${GITHUB_WORKSPACE}/.github/web-viewer \
            --gh-raw-pdf-url="https://raw.githubusercontent.com/NotXia/unibo-ai-notes/pdfs"

      - name: Move to pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pages
          FOLDER: /tmp/webviewer
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: "github-actions[bot]"
          COMMIT_EMAIL: "github-actions[bot]@users.noreply.github.com"
          MESSAGE: "🤖 Web developer stuff"
          SKIP_EMPTY_COMMITS: true